require 'rubygems'
require 'rake/gempackagetask'
require 'spec/rake/spectask'
require 'merb-core/tasks/merb_rake_helper'

NAME = "merb_param_protection"
GEM_VERSION = "0.9.4"
AUTHOR = "Lance Carlson"
EMAIL = "lancecarlson@gmail.com"
HOMEPAGE = "http://merbivore.com/"
SUMMARY = "Merb plugin that provides params_accessible and params_protected class methods"

spec = Gem::Specification.new do |s|
  s.rubyforge_project = 'merb'
  s.name = NAME
  s.version = GEM_VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.add_dependency('merb-core', '>= 0.9.4')
  s.require_path = 'lib'
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs}/**/*")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc "install merb_param_protection"
task :install => [:specs, :package] do
  sh %{#{sudo} gem install #{install_home} pkg/#{NAME}-#{GEM_VERSION} --no-rdoc --no-ri --no-update-sources}
end

namespace :jruby do

  desc "Run :package and install the resulting .gem with jruby"
  task :install => :package do
    sh %{#{sudo} jruby -S gem install #{install_home} pkg/#{NAME}-#{GEM_VERSION}.gem --no-rdoc --no-ri}
  end

end

desc "Run all specs"
Spec::Rake::SpecTask.new('specs') do |t|
  t.spec_opts = ["--format", "specdoc", "--colour"]
  t.spec_files = Dir['spec/**/*_spec.rb'].sort
end

desc "RCov"
Spec::Rake::SpecTask.new("rcov") do |t|
  t.rcov_opts = ["--exclude", "gems", "--exclude", "spec"]
  t.spec_opts = ["--format", "specdoc", "--colour"]
  t.rcov_opts = ["--exclude","gems", "--exclude", "spec"]
  t.spec_files = Dir["spec/**/*_spec.rb"].sort
  t.libs = ["lib", "server/lib" ]
  t.rcov = true
end


##############################################################################
# Release
##############################################################################
RUBY_FORGE_PROJECT = NAME

PKG_NAME      = NAME
PKG_BUILD     = ENV['PKG_BUILD'] ? '.' + ENV['PKG_BUILD'] : ''
PKG_VERSION   = GEM_VERSION + PKG_BUILD
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

RELEASE_NAME  = "REL #{PKG_VERSION}"

# FIXME: hey, someone take care of me
RUBY_FORGE_USER    = ""

require "extlib/tasks/release"
