require 'rubygems'
require 'rake/gempackagetask'

PLUGIN = "merb_active_record"
NAME = "merb_active_record"
VERSION = "0.0.1"
AUTHOR = "Ezra Zygmuntowicz"
EMAIL = "ez@engineyard.com"
HOMEPAGE = "http://merb-plugins.rubyforge.org/merb_active_record2/"
SUMMARY = "Merb plugin that provides ActiveRecord support"

spec = Gem::Specification.new do |s|
  s.name = NAME
  s.version = VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.requirements << ['merb', 'active_record']
  s.require_path = 'lib'
  s.autorequire = PLUGIN
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs}/**/*")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end