require "rubygems"
require "rake/gempackagetask"
require 'merb-core/tasks/merb_rake_helper'

NAME = "merb_sequel"
GEM_VERSION = "0.9.4"
AUTHOR = "Wayne E. Seguin, Lance Carlson"
EMAIL = "wayneeseguin@gmail.com, lancecarlson@gmail.com"
HOMEPAGE = "http://merbivore.com/"
SUMMARY = "Merb plugin that provides support for Sequel and Sequel::Model"

specification = Gem::Specification.new do |s|
  s.rubyforge_project = 'merb'
  s.name = NAME
  s.email = EMAIL
  s.author = AUTHOR
  s.version = GEM_VERSION
  s.summary = SUMMARY
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.homepage = HOMEPAGE
  s.description = SUMMARY
  s.require_path = "lib"
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']

  s.add_dependency("merb-core", ">= 0.9.4")
  s.add_dependency("sequel",    ">= 1.4.0")
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs,sequel_generators}/**/*")
end

Rake::GemPackageTask.new(specification) do |package|
  package.gem_spec = specification
end

desc "Install merb_sequel"
task :install => :package do
  sh %{#{sudo} gem install #{install_home} pkg/#{NAME}-#{GEM_VERSION} --no-rdoc --no-ri --no-update-sources}
end

namespace :jruby do

  desc "Run :package and install the resulting .gem with jruby"
  task :install => :package do
    sh %{#{sudo} jruby -S gem install #{install_home} pkg/#{NAME}-#{GEM_VERSION}.gem --no-rdoc --no-ri}
  end

end