require 'rubygems'
require 'rake/gempackagetask'

PLUGIN = "merb_data_mapper"
NAME = "merb_data_mapper"
VERSION = "0.0.1"
AUTHOR = "Jason Toy"
EMAIL = "jtoy@rubynow.com"
HOMEPAGE = "http://merb-plugins.rubyforge.org/merb_data_mapper/"
SUMMARY = "Merb plugin that provides DataMapper support for Merb"

spec = Gem::Specification.new do |s|
  s.name = NAME
  s.version = VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.requirements << 'merb'
  s.require_path = 'lib'
  s.autorequire = PLUGIN
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs,merb_generators}/**/*")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

task :install do
  sh %{rake package}
  sh %{sudo gem install pkg/#{NAME}-#{VERSION}}
end
