require 'rubygems'
require 'rake/gempackagetask'

PLUGIN = "sampleplugin"
NAME = "merb-#{PLUGIN}"
VERSION = "0.1.2"
AUTHOR = "Michael D. Ivey"
EMAIL = "ivey@gweezlebur.com"
HOMEPAGE = "http://merb-plugins.rubyforge.org/merb-sampleplugin/"
SUMMARY = "Merb plugin that provides FROBAZZ"

spec = Gem::Specification.new do |s|
  s.name = NAME
  s.version = VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.requirements << 'merb'
  s.require_path = 'lib'
  s.autorequire = PLUGIN
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs}/**/*")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end